services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306

    environment:
      - MYSQL_DATABASE=culinaryapp
      - MYSQL_ROOT_PASSWORD=${PASSWORD}

    volumes:
      - ../msqldata:/var/lib/mysql

  django:

    build: .
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    environment:
      - DB_HOST=mysql

    depends_on:
      - mysql


    restart: on-failure
