services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306

    environment:
      - MYSQL_DATABASE=culinaryapp
      - MYSQL_ROOT_PASSWORD=${MYSQL_DB_PASSWORD}

    volumes:
      - ../msqldata:/var/lib/mysql

  django:
    build: .
    command: ./wait-for-it.sh mysql:3306 -- ./entrypoint.sh

    # ports:
    #   - "8000:8000"

    volumes:
      - .:/app

    environment:
      - DB_HOST=mysql
      - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}

    depends_on:
      - mysql


    restart: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  
      # - "443:443" # Map port 443 of the container to port 443 on the host
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/static
      - ./media:/app/media
    depends_on:
      - django
    restart: always

