# Generated by Django 5.0.6 on 2024-05-25 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinaryapp', '0002_rename_ingredients_dish_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='culinaryapp.ingredient'),
        ),
    ]
