# Generated by Django 5.0.6 on 2024-05-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinaryapp', '0003_alter_dishingredient_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rateds', to='culinaryapp.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='culinaryapp.dish'),
        ),
    ]
