# Generated by Django 5.0.6 on 2024-05-26 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinaryapp', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='culinaryapp.dish'),
        ),
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_tags', to='culinaryapp.dish')),
            ],
        ),
        migrations.CreateModel(
            name='DishTypeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_tag', models.CharField(max_length=255)),
                ('dish', models.ManyToManyField(through='culinaryapp.DishTag', to='culinaryapp.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dishtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinaryapp.dishtypetag'),
        ),
    ]
