# Generated by Django 5.0.6 on 2024-05-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinaryapp', '0006_alter_dishimage_dish_dishtag_dishtypetag_dishtag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culinaryapp.dish')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_dishes', to='culinaryapp.userprofile')),
            ],
        ),
    ]
