# Generated by Django 5.0.6 on 2024-05-28 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culinaryapp', '0008_chefprofile_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chefprofile',
            old_name='added_by',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='rater',
            new_name='profile',
        ),
    ]
