# Generated by Django 5.0.6 on 2024-05-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culinaryapp', '0009_rename_added_by_chefprofile_profile_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dishingredient',
            unique_together={('dish', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='dishtag',
            unique_together={('dish', 'tag')},
        ),
    ]
