name: CulinaryAPI CI/CD Pipeline

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ] 

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10
        ports:
          - 8000:8000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker images
      run: |
        docker-compose build

    - name: Start services
      run: |
        docker-compose up -d

    - name: Wait for MySQL to be ready
      run: |
        ./wait-for-it.sh mysql:3306 -- echo "MySQL is up"

    - name: Run migrations
      run: |
        docker-compose run --rm django python manage.py migrate

    - name: Run Tests
      run: |
        docker-compose run --rm django pytest


    - name: Stop and remove services
      if: always()
      run: |
        docker-compose down

  deploy:
    name: deploy to digitalocean
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps: 
      - name: deploy to Digitalocean
        uses: appleboy/ssh-action@v1.0.3
        with:
           host: ${{ secrets.SSH_HOST}}
           username: ${{ secrets.SSH_USERNAME}}
           key: ${{ secrets.SSH_PRIVATE_KEY}}

           script: |
             cd culinaryapp-api
             docker compose down
             git pull
             docker compose up --detach